package com.example.vanahel.tasksmanagerapplication.util.screenshot;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.view.View;

import java.io.File;

public class ScreenshotProvider {

    private Activity activity;

    public ScreenshotProvider(Activity activity) {
        this.activity = activity;
    }


    public void takeScreenshotShare() {
        View rootView = activity.getWindow().getDecorView().getRootView();
        File file = takeScreenshot(rootView);
        shareScreenshot(file);
    }

    private File takeScreenshot(View rootView) {
        Bitmap bitmap = ScreenshotUtil.getScreenShot(rootView);
        File saveFile = ScreenshotUtil.getMainDirectoryName(activity);
        File file = ScreenshotUtil.store(bitmap, "screenshot.jpg", saveFile);
        return file;

    }

    private void shareScreenshot(File file) {
        Uri uri = Uri.fromFile(file);
        Intent intent = new Intent();
        intent.setAction(Intent.ACTION_SEND);
        intent.setType("image/*");
        intent.putExtra(Intent.EXTRA_SUBJECT, "TaskManagerApplication Test Mail");
        intent.putExtra(Intent.EXTRA_TEXT, "This is an autogenerated mail from TaskManagerApplication");
        intent.putExtra(Intent.EXTRA_STREAM, uri);
        activity.startActivity(Intent.createChooser(intent, "share"));
    }
}
